version: '3.7'


# container to run tests and other developer activities
services:
  php:
    container_name: cbrf-service-php
    image: cbrf-service-php
    build:
      context: php
    volumes:
      - ./../:/var/app:cached
